services: 
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
